using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Domain
{
    /// <summary>
    /// These classes are used to generate database in DAL.IDApplicationDbContext.cs
    /// Database with specified fields is generated by classname.
    /// Fields got constraints (eg. max and min length).
    /// Question mark in front of DateTime indicates field that is not required.
    /// Need klassid on selle jaoks, et kasutada andmebaasi genereerimist DAL.IDApplicationDbContext.cs-is
    /// Klassinime järgi genereeritakse anmdebaas väljadega, mis siin klassis eksisteerivad.
    /// Väljadele on pandud piirangud peale (näiteks maksimaalsed ja minimaalsed pikkused).
    /// Küsimärk DateTime ees sümboliseerib välja, mida ei ole otseselt vaja et päringut andmebaasi pihta teha.
    /// </summary>
    public class Log
    {
        [Key]
        public int LogId { get; set; }

        [MinLength(3)]
        [MaxLength(160)]
        public string LogText { get; set; }

        public DateTime? Added { get; set; }

        public DateTime? Deleted { get; set; }

        public DateTime? Updated { get; set; }
    }
}
